### PR TITLE
Fix subtitles files with same name

### PR DESCRIPTION
**Pull request by fdrissi**
If a movie has subtitles with the same name, the second one will overwrite the first one, so you get only one result.
for example this movie id: tt6398184
with these languages: langs: ["en", "fr"].
I replaces spaces from the subtitle filename, and i added the specified language to the name.
i.e: fileName: 'Downton.Abbey_french_.srt'

### CODE REVIEW

**Comment by mrdotb** [comment]
Thanks for the PR I will review and merge Wednesday.

**Comment by mrdotb** [comment]
I look at it but it broke the tests.
Use ```npm run test```
Can you use xo for linting ?

**Comment by fdrissi** [comment]
all green now.

**Comment by mrdotb** [comment]
:+1: Merged and published good luck for hypertude  :)

**Comment by fdrissi** [comment]
Thank you

**Pull request merged**
